name: Build and Share APK with QR

on:
  pull_request:
    branches:
      - "*"

permissions:
  pull-requests: write
  contents: read

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies
        run: |
          npm install
          npx expo install

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Clean and Build APK
        run: |
          cd android
          ./gradlew clean
          ./gradlew assembleDebug --info --stacktrace

      - name: Upload APK to GitHub Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk

      - name: Generate QR Code
        run: |
          ARTIFACT_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}#artifacts"
          QR_CODE="https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=${ARTIFACT_URL}"
          echo "![QR Code]($QR_CODE)" >> $GITHUB_STEP_SUMMARY

      - name: Post QR code comment on PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            🚀 APK is ready for testing! 
            [Download APK from GitHub Artifacts](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}#artifacts)

            ![QR Code](https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}#artifacts)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
